name: Change Request
description: Report an inaccuracy, typo, error, etc.
title: "[Change]: "
body:
  - type: dropdown
    id: location
    attributes:
      label: Where did you find the issue?
      multiple: true
      options:
        - Book
        - Wiki (Online Resources)
        - Github Code Repo
  - type: dropdown
    id: levels
    attributes:
      label: Which level(s) does this affect?
      multiple: true
      options:
        - 1 - Turtle Map
        - 2 - Class Introductions
        - 3 - Classroom Quiz
        - 4 - Space Wars
        - 5 - Creeper Chase
        - 6 - Boss Battle
        - 7 - IncrediCards
        - N/A
  - type: textarea
    id: change
    attributes:
      label: What did we get wrong? 
      description: Add any relevant information, including images (drag and drop below) and thoughts on how we should fix it!
      placeholder: The Cryptic Creeper corrupted the code by ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The Power Posse is on the case.
