name: Idea
description: Make a suggestion for improvement!
title: "[Idea]: "
body:
  - type: dropdown
    id: levels
    attributes:
      label: "Relevant level(s), if any:"
      multiple: true
      options:
        - 1 - Turtle Map
        - 2 - Class Introductions
        - 3 - Classroom Quiz
        - 4 - Space Wars
        - 5 - Creeper Chase
        - 6 - Boss Battle
        - 7 - IncrediCards
        - N/A
  - type: textarea
    id: idea
    attributes:
      label: "What's your suggestion?"
      placeholder: Cool idea here...
    validations:
      required: true
